Make the conv_apex_manifest subparser argument required
Previously, running conv_apex_manifest with no arguments would
give an "AttributeError: 'Namespace' object has no attribute 'func'".

After this cl it will print "conv_apex_manifest: error: the following
arguments are required: {strip,proto,setprop,print}"

Test: m conv_apex_manifest && ./out/host/linux-x86/bin/conv_apex_manifest
Change-Id: Ie3788fe0518f03a37ab258a65ff1903de1ab6227